# the name of the current app
spring:
  application:
    name: spring-boot-web-demo

  # indent the returned JSON responses
  jackson:
      serialization:
        INDENT_OUTPUT: true

# logging settings
logging:
  level:
    root: info
    io:
      undertow: error
    org:
      apache: warn
      eclipse: warn
      springframework: warn
      xnio: error
  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'